CREATE USER 'java'@'localhost'
IDENTIFIED BY PASSWORD '*59EF2F4BA9DC232297F351BDBA46FBCAE49326C4';

GRANT ALL
ON map.*
TO 'java'@'localhost';

FLUSH PRIVILEGES;

CREATE SCHEMA IF NOT EXISTS `map`
CHARACTER SET `utf8`
COLLATE `utf8_general_ci`;